
package view;
import javax.swing.JOptionPane;


public class TelaGerente extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerente
     */
    public TelaGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telacadastro1 = new javax.swing.JDesktopPane();
        telacadastro2 = new javax.swing.JDesktopPane();
        Flist_painel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_cadastrarF = new javax.swing.JMenuItem();
        menu_alterarDados = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Menu_CadastrarT = new javax.swing.JMenuItem();
        menu_attStatus = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Menu_sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 200));

        javax.swing.GroupLayout Flist_painelLayout = new javax.swing.GroupLayout(Flist_painel);
        Flist_painel.setLayout(Flist_painelLayout);
        Flist_painelLayout.setHorizontalGroup(
            Flist_painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        Flist_painelLayout.setVerticalGroup(
            Flist_painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        telacadastro2.setLayer(Flist_painel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telacadastro2Layout = new javax.swing.GroupLayout(telacadastro2);
        telacadastro2.setLayout(telacadastro2Layout);
        telacadastro2Layout.setHorizontalGroup(
            telacadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Flist_painel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        telacadastro2Layout.setVerticalGroup(
            telacadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Flist_painel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        telacadastro1.setLayer(telacadastro2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telacadastro1Layout = new javax.swing.GroupLayout(telacadastro1);
        telacadastro1.setLayout(telacadastro1Layout);
        telacadastro1Layout.setHorizontalGroup(
            telacadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telacadastro2)
        );
        telacadastro1Layout.setVerticalGroup(
            telacadastro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telacadastro2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jMenu1.setText("Arquivos");

        jMenuItem4.setText("Ver lista de Funcionários");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Ver lista de Tarefas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Funcionários");

        menu_cadastrarF.setText("Cadastrar");
        menu_cadastrarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastrarFActionPerformed(evt);
            }
        });
        jMenu2.add(menu_cadastrarF);

        menu_alterarDados.setText("Alterar dados");
        menu_alterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_alterarDadosActionPerformed(evt);
            }
        });
        jMenu2.add(menu_alterarDados);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tarefas");

        Menu_CadastrarT.setText("Cadastrar");
        Menu_CadastrarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_CadastrarTActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_CadastrarT);

        menu_attStatus.setText("Atualizar Status");
        jMenu3.add(menu_attStatus);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sair");

        Menu_sair.setText("Deslogar");
        Menu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_sairActionPerformed(evt);
            }
        });
        jMenu4.add(Menu_sair);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telacadastro1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telacadastro1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // COMANDOS DAS OPÇÕES DE INTERFACE
    
    private void menu_alterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_alterarDadosActionPerformed
        
    }//GEN-LAST:event_menu_alterarDadosActionPerformed

    private void menu_cadastrarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastrarFActionPerformed
        // Menu "Funcionario": click em CADASTRAR funcionário
        TelaCadastroFuncionario telaCadFunc = new TelaCadastroFuncionario();
        
        telacadastro1.add(telaCadFunc);
        telaCadFunc.setVisible(true);
        
    }//GEN-LAST:event_menu_cadastrarFActionPerformed

    // CADASTRAR TAREFAS
    private void Menu_CadastrarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_CadastrarTActionPerformed
        // Menu "Tarefa": click em CADASTRAR tarefas
        TelaCadastroTarefa cadTarefa = new TelaCadastroTarefa();
        
        // abre a tela de cadastro de tarefas
        telacadastro2.add(cadTarefa);
        cadTarefa.setVisible(true);
                
    }//GEN-LAST:event_Menu_CadastrarTActionPerformed
      
    // abrir lista de funcionarios (incompleta)
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      
      ListaFuncionarios Flist = new ListaFuncionarios();
      Flist_painel.add(Flist);
      Flist.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void Menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_sairActionPerformed
      // opção "Deslogar" no menu Sair
        try{
            // caixa de mensagem de confirmação
                int opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", null, JOptionPane.YES_NO_OPTION);
            
                if (opcao == JOptionPane.YES_OPTION)
                {   
                    login Login = new login();
                    Login.setVisible(true);
                    dispose();  
                }
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro\nTente Novamente", "ERROR", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_Menu_sairActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Flist_painel;
    private javax.swing.JMenuItem Menu_CadastrarT;
    private javax.swing.JMenuItem Menu_sair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem menu_alterarDados;
    private javax.swing.JMenuItem menu_attStatus;
    private javax.swing.JMenuItem menu_cadastrarF;
    private javax.swing.JDesktopPane telacadastro1;
    private javax.swing.JDesktopPane telacadastro2;
    // End of variables declaration//GEN-END:variables
}
